name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm install
      - run: npm test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: testsReport
          path: |
            report.html
            jest-html-reporters-attach/report