name: Tests

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - run: npm install
      - run: npm test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: testsReport
          path: jest-html-reporters-attach.html
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html-report
          clean: true
          token: ${{ secrets.TOKEN }}

      - name: Send report via telegram bot
        run: "curl -X POST https://api.telegram.org/bot${{secrets.BOT_TOKEN}}/sendMessage -H \"Content-Type: application/json\" -d '{\"chat_id\": \"${{secrets.CHAT_ID}}\", \"text\": \"Hello world from public repo!\"}'"