name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm install
      - run: npm test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: testsReport
          path: |
            report.html
            jest-html-reporters-attach/report

      - name: Send report via telegram bot
        run: "curl -X POST https://api.telegram.org/bot${{secrets.BOT_TOKEN}}/sendMessage -H \"Content-Type: application/json\" -d '{\"chat_id\": \"${{secrets.CHAT_ID}}\", \"text\": \"Hello world from bot!\"}'" 